services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:16
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=ms_pedido
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"